spring:
  application:
    name: smartbuildings
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_build_safe?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    username: root
    password: lzhr20050315
  redis:
    client-type: jedis
    host: localhost
    port: 6379
    timeout: 5000ms
    connect-timeout: 3000ms
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

mybatis-plus:
  type-aliases-package: com.qst.smartbuildings.entity
  configuration:
    map-underscore-to-camel-case: true

device:
  tcp:
    port: 8888

camera:
  ai:
    baseUrl: http://localhost:5000/detect
  live:
    baseUrl: http://localhost:8068/hls/

tower:
  ai:
    baseUrl: http://localhost:5000/crane_safety

management:
  health:
    redis:
      enabled: false          # 禁用 Redis 健康检查
  endpoint:
    health:
      show-details: always
      show-components: always

logging:
  level:
    io.lettuce.core: DEBUG
    org.springframework.data.redis: DEBUG