spring:
  application:
    name: smart_warehousing
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_build_safe?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        shutdown-timeout: 100ms
        pool:
          max-active: 100
          max-wait: 50ms
      timeout: 200ms

server:
  port: 8080

mybatis-plus:
  type-aliases-package: com.qst.smart_warehousing.entity
  configuration:
    # ===== 开启 SQL 日志（定位问题后可按需关闭） =====
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

device:
  tcp:
    port: 8888

camera:
  ai:
    baseUrl: http://localhost:5000/detect
  live:
    baseUrl: http://localhost:8068/hls/

tower:
  ai:
    baseUrl: http://localhost:5000/crane_safety

logging:
  level:
    com.qst.smart_warehousing: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.authentication: DEBUG
    com.qst.smart_warehousing.mapper: DEBUG

ai:
  service:
    url: http://localhost:8001

# 视频转码服务配置
video:
  ffmpeg:
    path: D:/project/java/ffmpeg/bin/ffmpeg.exe          # 改成你自己的ffmpeg.exe路径
  test:
    source: D:\project\java\SmartWarehousing\backend\src\main\resources\test.mp4          # 测试用本地视频路径（没有摄像头就用这个）
  hls:
    output-dir: Y:\codingLog\codeart\nginx 1.7.11.3 Gryphon\html\hls          # HLS切片文件输出目录
    prefix: http://localhost:8081/hls/      # Nginx对外访问的HLS地址前缀
