spring:
  application:
    name: smart_warehousing
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_build_safe?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        shutdown-timeout: 100ms
        pool:
          max-active: 100
          max-wait: 50ms
      timeout: 200ms

server:
  port: 8080

mybatis-plus:
  type-aliases-package: com.qst.smart_warehousing.entity
  configuration:
    # ===== 开启 SQL 日志（定位问题后可按需关闭） =====
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

device:
  tcp:
    port: 8888

camera:
  ai:
    baseUrl: http://localhost:5000/detect
  live:
    baseUrl: http://localhost:8068/hls/

tower:
  ai:
    baseUrl: http://localhost:5000/crane_safety

logging:
  level:
    com.qst.smart_warehousing: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.authentication: DEBUG